accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

# 同じディレクトリ(今回はaccounts)からviews.pyをimportしている
from . import views  # .（ピリオド1つ）が同じディレクトリを表す

app_name = "accounts"

urlpatterns = [
    path(
        "signup/", views.signup, name="signup"
    ),  # 第三引数のnameはパターンネームといい、signup.htmlでビューを呼び出すために記述される
    path("login/", auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<str:username>/', views.user_profile_view,
         name='user_profile'),
    path('edit/<str:username>/', views.user_edit_view,
         name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",  namespace='accounts')),
    path("quiz/", include("quiz.urls",  namespace='quiz')),
    path("post/", include("post.urls",  namespace='post')),
    path("", include("welcome.urls",  namespace='welcome')),
]

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home/", views.PostView.as_view(), name="home"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()
    questions_num = models.IntegerField(default=0)
    answered_question_num = models.IntegerField(default=0)
    correct_num = models.IntegerField(default=0)
    incorrect_num = models.IntegerField(default=0)
    correct_rate = models.IntegerField(default=0)
    total_correct_rate = models.IntegerField(default=0)

    def player_result(self, correct_rate):
        self.correct_rate = correct_rate
        return correct_rate

accounts/forms.py
from typing import Any
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

User = get_user_model()  # こっちで先に変数代入する！


class SignupForm(UserCreationForm):
    class Meta:
        model = User  # model = get_user_model() は NG
        # オブジェクトを作成
        fields = ("username", "email")
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["username"].help_text = ''
        self.fields["password1"].help_text = ''
        self.fields["password2"].help_text = ''

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']  # 更新したいフィールドを指定

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # フォームの見た目をカスタマイズする場合は、ここで設定します。
        self.fields['username'].label = 'ユーザー名'
        self.fields['email'].label = 'メールアドレス'
        self.fields["username"].help_text = ''

accounts/views.py
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model, login,logout
from django.urls import reverse_lazy
from quiz.models import Player_result
from django.shortcuts import render, redirect
from django.db.models import Max, Min
from .forms import SignupForm, UserUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.db.models import Q
User = get_user_model()


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')  # Use password1 for password field
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse_lazy(settings.LOGIN_REDIRECT_URL))  # Redirect to the success URL
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})


def user_profile_view(request, username):
    user = User.objects.get(username=username)  
    # usernameフィールドと受け取った入力値が等しくなるような行を抽出
    player_result = Player_result.objects.filter(user=user)
    print(player_result)
    # __gt=0で０より大きいレコードのみを抽出
    max_rate_invite = player_result.filter(flog_rate_invite__gt=0).aggregate(Max('flog_rate_invite'))['flog_rate_invite__max']
    max_rate_date = player_result.filter(flog_rate_date__gt=0).aggregate(Max('flog_rate_date'))['flog_rate_date__max']
    max_rate_confession = player_result.filter(flog_rate_confession__gt=0).aggregate(Max('flog_rate_confession'))['flog_rate_confession__max']
    min_rate_invite = player_result.filter(flog_rate_invite__gt=0).aggregate(Min('flog_rate_invite'))['flog_rate_invite__min']
    min_rate_date = player_result.filter(flog_rate_date__gt=0).aggregate(Min('flog_rate_date'))['flog_rate_date__min']
    min_rate_confession = player_result.filter(flog_rate_confession__gt=0).aggregate(Min('flog_rate_confession'))['flog_rate_confession__min']
    print(max_rate_invite)
    params = {
        'player_result': player_result,
        'username': username,
        'max_rate_invite': max_rate_invite,
        'max_rate_date': max_rate_date,
        'max_rate_confession': max_rate_confession,
        'min_rate_invite': min_rate_invite,
        'min_rate_date': min_rate_date,
        'min_rate_confession': min_rate_confession
    }
    return render(request, 'accounts/user_profile.html', params)


def user_edit_view(request, username):
    if request.method == 'POST':
        user = User.objects.get(username=username)
        user_form = UserUpdateForm(request.POST, instance=user)
        # password_form = PasswordChangeForm(request.user, request.POST)
        if user_form.is_valid():
            user_form.save()
            username = user_form.cleaned_data['username']
            url = reverse_lazy('accounts:user_profile',
                               kwargs={'username': username})
            # password_form.save()
            # update_session_auth_hash(request, password_form.user)
            # username=usernameで更新後にユーザーごとのプロフィールページにリダイレクト
            return redirect(url, username=username)
    else:
        user = User.objects.get(username=username)
        user_form = UserUpdateForm(instance=user)
        # password_form = PasswordChangeForm(request.user)

    params = {
        'user_form': user_form,
        # 'password_form': password_form,
    }
    return render(request, 'accounts/edit.html', params)


class ProfileEditView(LoginRequiredMixin, UpdateView): # 追加
    template_name = 'accounts/edit.html'
    model = User
    form_class = UserUpdateForm
    success_url = '/accounts/edit/'
    
    def get_object(self):
        return self.request.user

templates/accounts/edit.html
{% extends "base.html" %}
{% load static %}
    {% block css %}<link href="{% static 'css/signup.css' %}" rel="stylesheet">{% endblock %}
    {% block title %}プロフィール編集{% endblock %}
{% block content %}
    <div class="top-wrapper">
      <div class="top-container">
        <div class="top-text"><img class="logo-login" src="{% static 'images/KKFrog.png' %}"></div>
        <div class="top-text"><h2>プロフィール編集</h2></div>
          <form method="post" class="top-address">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ password_form.as_p }}
            <button type="submit" class="login-btn">保存</button>
          </form>
        </div>
      </div>
    </div>
{% endblock %}
{% block script %}
    <script 
        src="https://code.jquery.com/jquery-3.7.1.js" 
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" 
        crossorigin="anonymous">
    </script>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block css %}<link href="{% static 'css/login.css' %}" rel="stylesheet">{% endblock %}
{% block title %}ログイン{% endblock %}
{% block content %}
    <div class="top-wrapper">
      <div class="top-container">
        <img class="logo-login" src="{% static 'images/KKFrog.png' %}">
        <div class="top-text"><h2>ログイン</h2></div>
          <form method="post" class="top-address">
              {{ form.as_p }}
            <!--formにはSignupFormのインスタンスが入っている。as_pとすることで、各input要素(クラス内に定義した要素)がpタグで囲まれた状態で表示される。-->
            <!--<p>{{ form.username.label }} {{ form.username }}</p>
            <p>{{ form.password.label }} {{ form.password }}</p>-->
            {% csrf_token %}
            <button type="submit" class="login-btn">ログイン</button>
          </form>
          <div class="no-account">
            <label>アカウントを持っていない</label>
            <a href="{% url 'accounts:signup' %}">新規登録</a>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
    {% block script %}
    <script 
        src="https://code.jquery.com/jquery-3.7.1.js" 
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" 
        crossorigin="anonymous">
    </script>
    {% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}
    {% block css %}<link href="{% static 'css/signup.css' %}" rel="stylesheet">{% endblock %}
    {% block title %}サインアップ{% endblock %}
{% block content %}
    <div class="top-wrapper">
      <div class="top-container">
        <div class="top-text"><img class="logo-login" src="{% static 'images/KKFrog.png' %}"></div>
        <div class="top-text"><h2>新規登録</h2></div>
          <form method="post" action="{% url 'accounts:signup' %}" class="top-address">
            {{ form.as_p }} <!--formにはSignupFormのインスタンスが入っている。as_pとすることで、各input要素(クラス内に定義した要素)がpタグで囲まれた状態で表示される。-->
            <!--<p>{{ form.username.label }} {{ form.username }}</p>
            <p>{{ form.email.label }} {{ form.email }}</p>
            <p>{{ form.password1.label }} {{ form.password1 }}</p>
            <p>{{ form.password2.label }} {{ form.password2 }}</p>-->
            {% csrf_token %}
            <button type="submit" class="login-btn">ユーザー登録</button>
          </form>
          <div class="no-account">
            <label>アカウントを持っている</label>
            <a href="{% url 'accounts:login' %}">ログイン</a>
          </div>
      </div>
    </div>
{% endblock %}
{% block script %}
    <script 
        src="https://code.jquery.com/jquery-3.7.1.js" 
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" 
        crossorigin="anonymous">
    </script>
{% endblock %}

templates/accounts/user_profile.html
{% extends "base.html" %}
{% load static %}
    {% block css %}<link href="{% static 'css/userprofile.css' %}" rel="stylesheet" >{% endblock %}
    {% block title %}ユーザー情報{% endblock %}
{% block content %}
    <div class="userinfo">
        <div class="container">
            <div class="user">
                <h3>ユーザー情報</h3>
                {{username}}
                <div class="change">
                    <a href="{% url 'accounts:edit' user.username %}" style="text-decoration: none;" class="login-btn">登録情報の変更</a>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="scoreinfo">
                <div class="rireki">
                    <h3>スコア情報</h3>
                    <div class="min-container">
                        <label class="label">ハイスコア</label>
                        <div class="smallbox">
                            {%if min_rate_invite == 1 %}
                            <span class="text">デートの誘い方編</span><span class="value">0%</span>
                            {% else %}
                            <span class="text">デートの誘い方編</span><span class="value">{{min_rate_invite}}%</span>
                            {% endif %}
                        </div>
                        <div class="smallbox">
                            {%if min_rate_date == 1 %}
                            <span class="text">デートの誘い方編</span><span class="value">0%</span>
                            {% else %}
                            <span class="text">デート中編</span><span class="value">{{min_rate_date}}%</span>
                            {% endif %}
                        </div>
                        <div class="smallbox">
                            {%if min_rate_confession == 1 %}
                            <span class="text">デートの誘い方編</span><span class="value">0%</span>
                            {% else %}
                            <span class="text">告白前のデート編</span><span class="value">{{min_rate_confession}}%</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="max-container">
                        <label class="label">ロースコア</label>
                        <div class="smallbox">
                            <span class="text">デートの誘い方編</span><span class="value">{{max_rate_invite}}%</span>
                        </div>
                        <div class="smallbox">
                            <span class="text">デート中編</span><span class="value">{{max_rate_date}}%</span>
                        </div>
                        <div class="smallbox">
                            <span class="text">告白前のデート編</span><span class="value">{{max_rate_confession}}%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script 
        src="https://code.jquery.com/jquery-3.7.1.js" 
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" 
        crossorigin="anonymous">
    </script>
{% endblock %}