accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

# 同じディレクトリ(今回はaccounts)からviews.pyをimportしている
from . import views  # .（ピリオド1つ）が同じディレクトリを表す

app_name = "accounts"

urlpatterns = [
    path(
        "signup/", views.signup, name="signup"
    ),  # 第三引数のnameはパターンネームといい、signup.htmlでビューを呼び出すために記述される
    path("login/", auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<str:username>/', views.user_profile_view,
         name='user_profile'),
    path('edit/<str:username>/', views.user_edit_view,
         name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",  namespace='accounts')),
    path("quiz/", include("quiz.urls",  namespace='quiz')),
    path("post/", include("post.urls",  namespace='post')),
    path("", include("welcome.urls",  namespace='welcome')),
]

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home/", views.PostView.as_view(), name="home"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

quiz/urls.py
from django.urls import path

from . import views

app_name = "quiz"

urlpatterns = [
    path('question_invite/', views.question_invite_view, name='question_invite'),
    path('question_date/', views.question_date_view, name='question_date'),
    path('question_confession/', views.question_confession_view, name='question_confession'),
    path('result_invite/', views.result_invite_view, name='result_invite'),
    path('result_date/', views.result_date_view, name='result_date'),
    path('result_confession/', views.result_confession_view, name='result_confession'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.welcome_view, name="welcome"),
]

welcome/models.py
from django.db import models

# Create your models here.

welcome/views.py
from quiz.models import Player_result
from django.shortcuts import render

from django.contrib.auth import get_user_model


User = get_user_model()


def welcome_view(request):
    params = {
        'user': request.user,
    }
    return render(request, 'welcome/welcome.html', params)

templates/welcome/welcome.html
{% extends "base.html" %}
{% block title %}ようこそ{% endblock %}
{% load static %}{% block css %}<link href="{% static 'css/welcome.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<div class="top-wrapper">
    <div class="container">
        <div class="top-contents">
          <img class="main-photo" src="{% static 'images/kaeruhome.png' %}">
          <img class="divide-photo" src="{% static 'images/区切り線１.png' %}">
          <div class="top-text">
            <h1>「カエル化回避！！」とは</h1>
            <p>「カエル化回避！！」は、あなたの「カエル化度」を計測できる診断サイトです。
                <br><span class="char-1">ルールは簡単！！！</span>
                <br>あるお題に対して、あなたが一番カエル化されないと思う解答を選ぶだけ！
                <br>それだけであなたの「カエル化度」(あなたの蛙化されてしまうかもしれない度合い)を計測できちゃいます。
                <br>すべてのシナリオで「カエル化度」０％になった時には、デートマスターになっているかも？！
                <br><span class="char-2">楽しみながら、たまにタメになる。</span>
                <br>そんな「カエル化回避！！」をぜひお楽しみください！！！
            </p>
          </div>
          <div class="top-alert">
            <h2>⚠注意⚠</h2>
            <p>「蛙化現象」とは本来「好意を抱いている相手が自分に好意を持っていることが明らかになると、その相手に対して嫌悪感を持つようになる現象」を指します。
              <br>しかし、このゲームで使われている「蛙化」は本来の意味とは異なり、
              <br>「恋愛感情や好意を抱いている相手のささいな言動が気になり、気持ちが急速に冷めてしまう」という意味で使用しております。
              <br>ご了承ください。多めにみてください。
              <br>P.S.　「蛙化現象」の対義語は「蛇化現象」と言うらしいです、初耳。
            </p>
          </div>
          <img class="divide-photo" src="{% static 'images/区切り線１.png' %}">
          <div class="determine">
            <div class="determine-container">
              <div class="determine-contents">
                <div class="determine-message">
                  <h1>＜さっそくゲームプレイ！＞</h1>
                </div>    
                {% if user.is_authenticated %}
                <div class="card-container">
                  <div class="card-contents">
                    <div class="card">
                      <a href="{% url 'quiz:question_invite' %}" style="text-decoration: none;">デートの誘い方編</a>
                      <p>気になる子ができたから
                        <br>デートに誘いたい！
                        <br>でも、誘い方がわからない！
                        <br>そんな人にきっと参考になる内容
                      </p>
                    </div>
                    <div class="card">
                      <a href="{% url 'quiz:question_date' %}" style="text-decoration: none;">デート中編</a>
                      <p>デート中には何を気にすれば良いのでしょうか？</p>
                    </div>
                    <div class="card">
                      <a href="{% url 'quiz:question_confession' %}" style="text-decoration: none;">告白編</a>
                      <p>告白のタイミングは？</p>
                    </div>
                    <div class="card">
                      <h3>Coming Soon ･･･</h3>
                    </div>
                  </div>
                  <div class="Arrow left">＜</div>
                  <div class="Arrow right">＞</div>
                </div>
                {% else %}
                <div class="determine-button">
                  <a href="{% url 'accounts:login' %}" class="button">Login</a>
                </div>
                {% endif %}
                
              </div>
            </div>
          </div>
          <img class="divide-photo" src="{% static 'images/区切り線１.png' %}">
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
  <script src="{% static 'javascripts/jquery.min.js' %}"></script>
  <script src="{% static 'javascripts/welcome.js' %}"></script>
  <script src="{% static 'javascripts/home.js' %}"></script>
{% endblock %}