accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

# 同じディレクトリ(今回はaccounts)からviews.pyをimportしている
from . import views  # .（ピリオド1つ）が同じディレクトリを表す

app_name = "accounts"

urlpatterns = [
    path(
        "signup/", views.signup, name="signup"
    ),  # 第三引数のnameはパターンネームといい、signup.htmlでビューを呼び出すために記述される
    path("login/", auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<str:username>/', views.user_profile_view,
         name='user_profile'),
    path('edit/<str:username>/', views.user_edit_view,
         name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",  namespace='accounts')),
    path("quiz/", include("quiz.urls",  namespace='quiz')),
    path("post/", include("post.urls",  namespace='post')),
    path("", include("welcome.urls",  namespace='welcome')),
]

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home/", views.PostView.as_view(), name="home"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

quiz/urls.py
from django.urls import path

from . import views

app_name = "quiz"

urlpatterns = [
    path('question_invite/', views.question_invite_view, name='question_invite'),
    path('question_date/', views.question_date_view, name='question_date'),
    path('question_confession/', views.question_confession_view, name='question_confession'),
    path('result_invite/', views.result_invite_view, name='result_invite'),
    path('result_date/', views.result_date_view, name='result_date'),
    path('result_confession/', views.result_confession_view, name='result_confession'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.welcome_view, name="welcome"),
]

quiz/models.py
from django.db import models
from django.conf import settings


class Quiz_invite(models.Model):
    """クイズの問題を表すモデル"""
    question = models.CharField(max_length=200, null=True)
    op1 = models.CharField(max_length=200, null=True)
    op2 = models.CharField(max_length=200, null=True)
    op3 = models.CharField(max_length=200, null=True)
    op4 = models.CharField(max_length=200, null=True)
 
    def __str__(self):
        return self.question

class Quiz_date(models.Model):
    """クイズの問題を表すモデル"""
    question = models.CharField(max_length=200, null=True)
    op1 = models.CharField(max_length=200, null=True)
    op2 = models.CharField(max_length=200, null=True)
    op3 = models.CharField(max_length=200, null=True)
    op4 = models.CharField(max_length=200, null=True)
 
    def __str__(self):
        return self.question

class Quiz_confession(models.Model):
    """クイズの問題を表すモデル"""
    question = models.CharField(max_length=200, null=True)
    op1 = models.CharField(max_length=200, null=True)
    op2 = models.CharField(max_length=200, null=True)
    op3 = models.CharField(max_length=200, null=True)
    op4 = models.CharField(max_length=200, null=True)
 
    def __str__(self):
        return self.question


class Player_result(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    flog_rate_invite = models.IntegerField(default=0)
    flog_rate_date = models.IntegerField(default=0)
    flog_rate_confession = models.IntegerField(default=0)

quiz/views.py
from django.views.generic import TemplateView
from .models import Quiz_date,Quiz_invite,Quiz_confession, Player_result
from django.shortcuts import render
from django.contrib.auth import get_user_model

User = get_user_model()

def question_invite_view(request):
    questions = Quiz_invite.objects.all()
    params = {
            'user': request.user,
            'questions': questions,
        }
    return render(request, 'quiz/question_invite.html', params)

def question_date_view(request):
    questions = Quiz_date.objects.all()
    params = {
            'user': request.user,
            'questions': questions,
        }
    return render(request, 'quiz/question_date.html', params)

def question_confession_view(request):
    questions = Quiz_confession.objects.all()
    params = {
            'user': request.user,
            'questions': questions,
        }
    return render(request, 'quiz/question_confession.html', params)

def result_invite_view(request):
    if request.method == 'POST':
        questions = Quiz_invite.objects.all()
        situaton1_score = 0
        correct = 0
        answered_num_invite = 0
        situation1_list = []
        player = request.user
        for q in questions:
            answered_num_invite += 1
            print(request.POST.get(q.question))
            if q.op1 == request.POST.get(q.question):
                situaton1_score += 0
                correct += 1
                situation1_list.append("great")
            elif q.op2 == request.POST.get(q.question):
                situaton1_score += 1
                situation1_list.append("good")
            elif q.op3 == request.POST.get(q.question):
                situaton1_score += 2
                situation1_list.append("frog")
            elif q.op4 == request.POST.get(q.question):
                situaton1_score += 3
                situation1_list.append("super frog")
        percent = situaton1_score/(answered_num_invite*3) * 100
        if percent == 0:
            percent = 1
        else:
            pass
        # Player_resultのデータを変数に格納
        player_result_invite = Player_result.objects.create(user=player, flog_rate_invite=percent)
        print(Player_result.objects.all().values())
        # 変数にsave()メソッドを適用してデータベースに保存
        player_result_invite.save()

        percent = player.player_result(percent)
        player.save()
        params = {
            'percent': int(percent),
            'answered_num': answered_num_invite,
            'situation1_list':situation1_list,
        }
        return render(request, 'quiz/result_invite.html', params)

    else:
        params = {
            'user': request.user,  
        }
        return render(request, 'quiz/question_invite.html', params)

def result_date_view(request):
    if request.method == 'POST':
        questions = Quiz_date.objects.all()
        situaton2_score = 0
        correct = 0
        answered_num_date = 0
        situation2_list=[]
        player = request.user
        for q in questions:
            answered_num_date += 1
            print(request.POST.get(q.question))
            if q.op1 == request.POST.get(q.question):
                situaton2_score += 0
                correct += 1
                situation2_list.append("great")
            elif q.op2 == request.POST.get(q.question):
                situaton2_score += 1
                situation2_list.append("good")
            elif q.op3 == request.POST.get(q.question):
                situaton2_score += 2
                situation2_list.append("frog")
            elif q.op4 == request.POST.get(q.question):
                situaton2_score += 3
                situation2_list.append("super frog")
        percent = situaton2_score/(answered_num_date*3) * 100
        if percent == 0:
            percent = 1
        else:
            pass
        # Player_resultのデータを変数に格納
        player_result_date = Player_result.objects.create(user=player, flog_rate_date=percent)
        print(Player_result.objects.all().values())
        # 変数にsave()メソッドを適用してデータベースに保存
        player_result_date.save()

        percent = player.player_result(percent)
        player.save()
        params = {
            'percent': int(percent),
            'answered_num_date': answered_num_date,
            'situation2_list':situation2_list,
        }
        return render(request, 'quiz/result_date.html', params)

    else:
        params = {
            'user': request.user,  
        }
        return render(request, 'quiz/question_date.html', params)
    
def result_confession_view(request):
    if request.method == 'POST':
        questions = Quiz_confession.objects.all()
        situaton3_score = 0
        correct = 0
        answered_num_confession = 0
        situation3_list=[]
        player = request.user
        for q in questions:
            answered_num_confession += 1
            print(request.POST.get(q.question))
            if q.op1 == request.POST.get(q.question):
                situaton3_score += 0
                correct += 1
                situation3_list.append("great")
            elif q.op2 == request.POST.get(q.question):
                situaton3_score += 1
                situation3_list.append("good")
            elif q.op3 == request.POST.get(q.question):
                situaton3_score += 2
                situation3_list.append("feog")
            elif q.op4 == request.POST.get(q.question):
                situaton3_score += 3
                situation3_list.append("super frog")
        percent = situaton3_score/(answered_num_confession*3) * 100
        if percent == 0:
            percent = 1
        else:
            pass
        # Player_resultのデータを変数に格納
        player_result_confession = Player_result.objects.create(user=player, flog_rate_confession=percent)
        print(Player_result.objects.all().values())
        # 変数にsave()メソッドを適用してデータベースに保存
        player_result_confession.save()

        percent = player.player_result(percent)
        player.save()
        params = {
            'percent': int(percent),
            'answered_num_confession': answered_num_confession,
            'situation3_list':situation3_list
        }
        return render(request, 'quiz/result_confession.html', params)

    else:
        params = {
            'user': request.user,  
        }
        return render(request, 'quiz/question_confession.html', params)

class HomeView(TemplateView):
    template_name = 'quiz/home.html'

templates/quiz/home.html
{% extends 'quiz/base.html' %}
{% block content %}
homeです
<li><a href="{% url 'quiz:question' %}">問題</a></li>
<li><a href="{% url 'accounts:user_profile' %}">ユーザーページ</a></li>
{% endblock %}

templates/quiz/question_confession.html
{% extends "base.html" %}
{% load static %}
{% block title %}Quiz{% endblock %}
{% block css %}<link href="{% static 'css/quiz.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<form action="{% url 'quiz:result_confession' %}" method='post' >
<div class="top-wrapper">
  <div class="container" id="quiz-cotainer">
    {% csrf_token %}
    {% for q in questions %}
    <div class="quiz" id="quiz-{{ forloop.counter }}" style="display: {% if forloop.first %} block {% else %}none{% endif %};">
      <div class="question-scenario">
        <h2>デートの誘い方編</h2>
      </div>
      <div class="illustration" >
          <img src="{% static 'images/kaeruhome.png' %}">
      </div>
      <div class="question">
        <h2>{{q.question}}</h2>
      </div>
      <div class="quiz-wrapper">
        <div class="box">
            <input type="radio" name="{{q.question}}" value="{{q.op1}}" id="option-{{ forloop.counter }}-1">
            <input type="radio" name="{{q.question}}" value="{{q.op2}}" id="option-{{ forloop.counter }}-2">
            <input type="radio" name="{{q.question}}" value="{{q.op3}}" id="option-{{ forloop.counter }}-3">
            <input type="radio" name="{{q.question}}" value="{{q.op4}}" id="option-{{ forloop.counter }}-4">
            <label for="option-{{ forloop.counter }}-1" class="option-1 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op1}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-2" class="option-2 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op2}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-3" class="option-3 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op3}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-4" class="option-4 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op4}}</div>
            </label>
        </div>
      </div>
      <div class="cq-btn-first">
        <button type="button" class="before-btn cq-btn" onclick="showBeforeQuiz({{ forloop.counter }}, {{ forloop.length }})"
                style="display: {% if forloop.first %} none {% else %} block {% endif %};">前の問題へ</button>
        <button type="button" class="next-btn cq-btn" onclick="showNextQuiz({{ forloop.counter }}, {{ forloop.length }})"
                style="display: {% if forloop.last %} none {% else %} block {% endif %};">次の問題へ</button>
      </div>
      <div class="cq-btn-last">
        
      </div>
      <button type="submit" class="btn btn-primary submit-btn" style="display: {% if forloop.last %} block {% else %} none {% endif %};">蛙化度計測&解説へ</button>
    </div>
    {% endfor %}
    </form>
  </div>
</div>

{% endblock %}
{% block script %}
  <script src="{% static 'javascripts/jquery.min.js' %}"></script>
  <script src="{% static 'javascripts/quiz.js' %}"></script>
{% endblock %}

templates/quiz/question_date.html
{% extends "base.html" %}
{% load static %}
{% block title %}Quiz{% endblock %}
{% block css %}<link href="{% static 'css/quiz.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<form action="{% url 'quiz:result_date' %}" method='post' >
<div class="top-wrapper">
  <div class="container" id="quiz-cotainer">
    {% csrf_token %}
    {% for q in questions %}
    <div class="quiz" id="quiz-{{ forloop.counter }}" style="display: {% if forloop.first %} block {% else %}none{% endif %};">
      <div class="question-scenario">
        <h2>デートの誘い方編</h2>
      </div>
      <div class="illustration" >
          <img src="{% static 'images/kaeruhome.png' %}">
      </div>
      <div class="question">
        <h2>{{q.question}}</h2>
      </div>
      <div class="quiz-wrapper">
        <div class="box">
            <input type="radio" name="{{q.question}}" value="{{q.op1}}" id="option-{{ forloop.counter }}-1">
            <input type="radio" name="{{q.question}}" value="{{q.op2}}" id="option-{{ forloop.counter }}-2">
            <input type="radio" name="{{q.question}}" value="{{q.op3}}" id="option-{{ forloop.counter }}-3">
            <input type="radio" name="{{q.question}}" value="{{q.op4}}" id="option-{{ forloop.counter }}-4">
            <label for="option-{{ forloop.counter }}-1" class="option-1 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op1}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-2" class="option-2 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op2}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-3" class="option-3 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op3}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-4" class="option-4 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op4}}</div>
            </label>
        </div>
      </div>
      <div class="cq-btn-first">
        <button type="button" class="before-btn cq-btn" onclick="showBeforeQuiz({{ forloop.counter }}, {{ forloop.length }})"
                style="display: {% if forloop.first %} none {% else %} block {% endif %};">前の問題へ</button>
        <button type="button" class="next-btn cq-btn" onclick="showNextQuiz({{ forloop.counter }}, {{ forloop.length }})"
                style="display: {% if forloop.last %} none {% else %} block {% endif %};">次の問題へ</button>
      </div>
      <div class="cq-btn-last">
        
      </div>
      <button type="submit" class="btn btn-primary submit-btn" style="display: {% if forloop.last %} block {% else %} none {% endif %};">蛙化度計測&解説へ</button>
    </div>
    {% endfor %}
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
  <script src="{% static 'javascripts/jquery.min.js' %}"></script>
  <script src="{% static 'javascripts/quiz.js' %}"></script>
{% endblock %}

templates/quiz/question_invite.html
{% extends "base.html" %}
{% load static %}
{% block title %}Quiz{% endblock %}
    {% block css %}<link href="{% static 'css/quiz.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<form action="{% url 'quiz:result_invite' %}" method='post' >
<div class="top-wrapper">
  <div class="container" id="quiz-cotainer">
    {% csrf_token %}
    {% for q in questions %}
    <div class="quiz" id="quiz-{{ forloop.counter }}" style="display: {% if forloop.first %} block {% else %}none{% endif %};">
      <div class="question-scenario">
        <h2>デートの誘い方編</h2>
      </div>
      <div class="illustration" >
          <img src="{% static 'images/kaeruhome.png' %}">
      </div>
      <div class="question">
        <h2>{{q.question}}</h2>
      </div>
      <div class="quiz-wrapper">
        <div class="box">
            <input type="radio" name="{{q.question}}" value="{{q.op1}}" id="option-{{ forloop.counter }}-1">
            <input type="radio" name="{{q.question}}" value="{{q.op2}}" id="option-{{ forloop.counter }}-2">
            <input type="radio" name="{{q.question}}" value="{{q.op3}}" id="option-{{ forloop.counter }}-3">
            <input type="radio" name="{{q.question}}" value="{{q.op4}}" id="option-{{ forloop.counter }}-4">
            <label for="option-{{ forloop.counter }}-1" class="option-1 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op1}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-2" class="option-2 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op2}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-3" class="option-3 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op3}}</div>
            </label>
            <label for="option-{{ forloop.counter }}-4" class="option-4 option-label">
                <div class="dot"></div>
                <div class="text">{{q.op4}}</div>
            </label>
        </div>
      </div>
      <div class="cq-btn-first">
        <button type="button" class="before-btn cq-btn" onclick="showBeforeQuiz({{ forloop.counter }}, {{ forloop.length }})"
                style="display: {% if forloop.first %} none {% else %} block {% endif %};">前の問題へ</button>
        <button type="button" class="next-btn cq-btn" onclick="showNextQuiz({{ forloop.counter }}, {{ forloop.length }})"
                style="display: {% if forloop.last %} none {% else %} block {% endif %};">次の問題へ</button>
      </div>
      <div class="cq-btn-last">
        
      </div>
      <button type="submit" class="btn btn-primary submit-btn" style="display: {% if forloop.last %} block {% else %} none {% endif %};">蛙化度計測&解説へ</button>
    </div>
    {% endfor %}
    </form>
  </div>
</div>
{% endblock %}
{% block script %}
  <script src="{% static 'javascripts/jquery.min.js' %}"></script>
  <script src="{% static 'javascripts/quiz.js' %}"></script>
{% endblock %}

templates/quiz/result.html
{% extends "base.html" %}
{% block title %}ようこそ{% endblock %}
{% load static %}{% block css %}<link href="{% static 'css/result.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<div class="top">
    <div class="result-container">
        <div class="result">
            <h3>\結果発表/</h3>
            <h4>&emsp;&emsp;&emsp;&emsp;蛙化度:<span class="char-1">&emsp;&emsp;{{percent}}</span>%</h4>
            <h4>解いた問題の数: &emsp;&emsp;{{answered_num}}</h4>
            <h4>各問題の蛙化度:&emsp;①〜％、②〜％、③〜％、④〜％</h4>
        </div>
        <div class="quiz-container">
            <h3>\解説/</h3>
            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">１問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                    <p><span>Great</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Good</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Frog</span>:クイズの解説文1がここに表示されます。</p>
                    <p><spna>Superfrog</spna>:クイズの解説文1がここに表示されます。</p>
                    <div class="explain">
                        <p><spna>全体の解説</p>
                    </div>
                </div>
            </div>
    
            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">２問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                    <p><span>Great</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Good</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Frog</span>:クイズの解説文1がここに表示されます。</p>
                    <p><spna>Superfrog</spna>:クイズの解説文1がここに表示されます。</p>
                    <div class="explain">
                        <p><spna>全体の解説</p>
                    </div>
                </div>
            </div>
    
            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">３問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                    <p><span>Great</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Good</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Frog</span>:クイズの解説文1がここに表示されます。</p>
                    <p><spna>Superfrog</spna>:クイズの解説文1がここに表示されます。</p>
                    <div class="explain">
                        <p><spna>全体の解説</p>
                    </div>
                </div>
            </div>

            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">４問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                    <p><span>Great</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Good</span>:クイズの解説文1がここに表示されます。</p>
                    <p><span>Frog</span>:クイズの解説文1がここに表示されます。</p>
                    <p><spna>Superfrog</spna>:クイズの解説文1がここに表示されます。</p>
                    <div class="explain">
                        <p><spna>全体の解説</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="btn">
            <a href="{% url 'welcome:welcome'%}" style="text-decoration: none;">ホーム画面に戻る</a>
        </div>
    </div>
</div>
{% block script %}
  <script src="result.js"></script>
  {% endblock %}

templates/quiz/result_confession.html
{% extends 'base.html' %}
{% load static %}
{% block css %}<link href="{% static 'css/result.css' %}" rel="stylesheet" >{% endblock %}
{% block title %}結果発表{% endblock %}
{% block content %}
<div class="top">
  <div class="top-wrapper">
    <div class="result-container">
        <div class="result">
            <h3>結果発表</h3>
            {%if percent == 1%}
            <h4 class="char-h4">&emsp;&emsp;&emsp;&emsp;蛙化度:<span class="char-1">&emsp;0&emsp;</span>%</h4>
            {% else %}
            <h4 class="char-h4">&emsp;&emsp;&emsp;&emsp;蛙化度:<span class="char-1">&emsp;{{percent}}&emsp;</span>%</h4>
            {%endif%}
            {% if percent >= 90  %}
            <h4>
              カエルになっちゃう！？
              <img src="../../static/images/Level3.png">
            </h4>
            {% elif percent >= 60 %}
            <h4>
              まあまあだね
              <img src="../../static/images/Level2.png">
            </h4>
            {% elif percent >= 40 %}
            <h4>
              よくやった
              <img src="../../static/images/Level1.png">
            </h4>
            {% else %}
            <h4>
              すばらしい！！
              <img src="../../static/images/Level0.png">
            </h4>
            {% endif %}
            {% for point in situation3_list %}
            <div class="card-text">
              第{{forloop.counter}}問目: {{point}}
            </div>
            {%endfor%} 
        </div>

        <div class="quiz-container">
            <h3>解説</h3>
            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">１問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                  <div class="great"><span>Great&emsp;:<span class="char-11">お台場周辺からの砂浜</span></span></div>
                  <p><span>Good&emsp;:<span class="char-11">超高級レストラン</span></p>
                  <p><span>Frog&emsp;:<span class="char-11">大衆居酒屋(うるさめ)</span></p>
                  <p><span>Superfrog&emsp;:<span class="char-11">心霊スポット</span></p>
                  <div class="explain">
                      <p><span>＜全体の解説＞</span></p>
                      <p>お台場は観光地として有名であり、夜景やデートスポットとしても人気があります!告白にはちょうど良い海岸沿いの砂浜があり、リラックス感とロマンティックな要素を兼ね備えていておすすめです！
                          <br>一見超高級レストランも雰囲気があり良さそうですが、恋人になるための告白にしては少し仰々しいかも…？
                      </p>
                  </div>
                </div>
            </div>
    
            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">２問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                  <div class="great"><span>Great&emsp;:<span class="char-10">「好きです、付き合ってください。」</span></span></div>
                  <p><span>Good&emsp;:<span class="char-10">「月が綺麗ですね」</span></p>
                  <p><span>Frog&emsp;:<span class="char-10">「とりま付き合って、だめなら別れよ？」</span></p>
                  <p><span>Superfrog&emsp;:<span class="char-10">「好き好き好き好き好き好き好き好き好き」</span></p>
                  <div class="explain">
                      <p><span>＜全体の解説＞</span></p>
                      <p>告白のフレーズで大事なことは「ストレートに、真剣に」気持ちを伝えることです。デートを重ねて気持ちを高め合っている状態なら、それだけ十分気持ちは伝わります！
                      </p>
                  </div>
                </div>
            </div>
    
            <div class="quiz-item">
                <div class="quiz-header">
                    <span class="question-number">３問目</span>
                    <button class="quiz-toggle-button">解説を表示 ⬇️</button>
                </div>
                <div class="quiz-content">
                  <div class="great"><span>Great&emsp;:<span class="char-10">デートの最後の方、クライマックスで</span></span></div>
                  <p><span>Good&emsp;:<span class="char-10">デート途中のお昼に</span></p>
                  <p><span>Frog&emsp;:<span class="char-10">朝集合したときに</span></p>
                  <p><span>Superfrog&emsp;:<span class="char-10">集合前にLINEで告白</span></p>
                  <div class="explain">
                      <p><span>＜全体の解説＞</span></p>
                      <p>デート中に感情が高まり、相手との距離感が近くなっていて雰囲気が最も良いのがディナー後のクライマックスです！このタイミングで告白することで成功確率もアップ！
                          <br>途中での告白は失敗した場合その後が…
                      </p>
                  </div>
                </div>
            </div>

        <div class="btn">
            <a href="{% url 'welcome:welcome'%}" style="text-decoration: none;">ホーム画面に戻る</a>
        </div>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
  <script src="{% static 'javascripts/jquery.min.js' %}"></script>
  <script src="{% static 'javascripts/result.js' %}"></script>
{% endblock %}