accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

# 同じディレクトリ(今回はaccounts)からviews.pyをimportしている
from . import views  # .（ピリオド1つ）が同じディレクトリを表す

app_name = "accounts"

urlpatterns = [
    path(
        "signup/", views.signup, name="signup"
    ),  # 第三引数のnameはパターンネームといい、signup.htmlでビューを呼び出すために記述される
    path("login/", auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('profile/<str:username>/', views.user_profile_view,
         name='user_profile'),
    path('edit/<str:username>/', views.user_edit_view,
         name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls",  namespace='accounts')),
    path("quiz/", include("quiz.urls",  namespace='quiz')),
    path("post/", include("post.urls",  namespace='post')),
    path("", include("welcome.urls",  namespace='welcome')),
]

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home/", views.PostView.as_view(), name="home"),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.welcome_view, name="welcome"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
</head>
<body>
  <header id="title">
    <div class="header-inner">
        <div class="header-left">
            <img class="logo" src="{% static 'images/KKFrog.png' %}">
        </div>
        <div class="header-right">
            <a href="{% url 'welcome:welcome'%}" style="text-decoration: none;">ホーム</a>
            {% if user.is_authenticated %}<!--ログイン状態-->
            <a href="{% url 'accounts:user_profile' user.username %}" style="text-decoration: none;">ユーザーページ</a>
            <a href="#" style="text-decoration: none;">投稿</a>
            <a href="{% url 'accounts:logout' %}" style="text-decoration: none;">ログアウト</a>
            {% else %}
            <a href="{% url 'accounts:login'%}" style="text-decoration: none;">ログイン</a>
            {% endif %}
        </div>
    </div>
  </header>
  {% block content %}{% endblock %}
  <footer>
    <div class="footer-wrapper">
      <ul class="footer-contents">
        <li>
            <a href="!" style="text-decoration: none;">トップ</a>
        </li>
        <li>
            <a href="!" style="text-decoration: none;">ヘルプ</a>
        </li>
        <li>
            <a href="!" style="text-decoration: none;">運営</a>
        </li>
        <li>
            <a href="!" style="text-decoration: none;">利用規約</a>
        </li>
        <li>
            <a href="!" style="text-decoration: none;">プライバシーポリシー</a>
        </li>
      </ul>
      <p>Copyright（C）Kenkashi Hakkason</p>
    </div>
  </footer>
  {% block script %}{% endblock %}
</body>
</html>